default:
  tags:
    - www-humo-tst-srv-runner

before_script:
  - docker system prune -af || true  # Очистка неиспользуемых образов и контейнеров
  - export NODE=/usr/bin/node
  - export NPM=/usr/bin/npm
  - export PATH=$NODE/bin:$PATH
  - export PATH=$NPM/bin:$PATH
  - node -v  
  - npm -v

build:
  stage: build
  when: manual
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - production


depploy:
  stage: deploy
  when: manual
  script:
    - cp -rf /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/src /app/public/src
    - cp -rf /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/config /app/public/config
    - cp -rf /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/types /app/public/types
    - cp -rf /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/.env /app/public/.env
    - docker stop humo-cms || true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stop $CI_REGISTRY_IMAGE:latest || true
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker run --rm -d -p 1337:1337 --name humo-cms -v /srv/app/public/uploads:/app/public/uploads -v /srv/app/src:/app/src -v /srv/app/config:/app/config -v /srv/app/types:/app/types -v /srv/app/.env:/app/.env $CI_REGISTRY_IMAGE:latest 
  allow_failure: true
  only:
    - production  